spring:
  application:
    name: lzhphantom-user-center
  datasource:
    hikari:
      maximum-pool-size: 100
      connection-timeout: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.79:3308/lzhphantom?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: 192.168.1.79
    database: 0
    password: root
server:
  port: 8011
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: lzhphantom_user接口文档
    version: v4.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lzhphantom.user_center.controller